- name: demo on vars
  hosts: local host
  vars:
    URL_play: play.example.com
  tasks:
   -  name: print variables
      ansible.builtin.debug:
        msg: URL_PLAY - {{ URL_PLAY }}

   - name: task variable
     ansible.builtin.debug:
       msg: URL_TASK - {{ URL_TASK }}
     vars:
       URL_TASK: tasks.example.com



# play level variables can be accessed by all roles and tasks
# tasks level variables is only accessed by that task only
#role level variables are accessed by in that role tasks
# variables from CLI have highest precendence of any variable

# imp: if the value of any key is a variable then double quote it
# example msg: {{URL}} THEN THIS AS TO BE GIVEN AS msg: "{{URL}}"

